#!/bin/bash
#SBATCH --job-name ablation_k_cut_preprocessing
#SBATCH --array=1-5
#SBATCH --partition=intelsr_medium
#SBATCH --time=24:00:00
#SBATCH --gpus=0
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=96
#SBATCH --exclusive
#SBATCH --output=logs/k_cut_preprocessing/ablation_large_%A_%a.out
#SBATCH --error=logs/k_cut_preprocessing/ablation_large_%A_%a.err

module load Gurobi

export OMP_NUM_THREADS=96

SCRIPT_DIR="slurm"
source "$SCRIPT_DIR/configs.sh"

i=${SLURM_ARRAY_TASK_ID}
seed=$((i-1))

for inst in "${instances_medium[@]}"; do
  for kval in "${k[@]}"; do
    for ((confIndex=0; confIndex<${#ablation_configs[@]}; confIndex++)); do
      if [ ! -e output/ablation_"$inst"_"$kval"_"${ablation_config_names[$confIndex]}"_"$seed".txt ]; then
        touch output/ablation_"$inst"_"$kval"_"${ablation_config_names[$confIndex]}"_"$seed".txt
        echo "Running ./build/ablationBenchmark -i instances/instances_clean/$inst -o output/ablation_"$inst"_"$kval"_"${ablation_config_names[$confIndex]}"_"$seed".txt -k $kval -d 1 -c ${ablation_configs[$confIndex]} -s $seed -t 1800"
        ./build/ablationBenchmark -i instances/instances_clean/$inst -o output/ablation_"$inst"_"$kval"_"${ablation_config_names[$confIndex]}"_"$seed".txt -k $kval ${ablation_configs[$confIndex]} -s $seed -t 1800
      fi
    done
  done
done
