#!/bin/bash
#SBATCH --job-name heuristic_k_cut_preprocessing
#SBATCH --array=1-3
#SBATCH --partition=intelsr_short
#SBATCH --time=04:00:00
#SBATCH --gpus=0
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=96
#SBATCH --exclusive
#SBATCH --output=logs/k_cut_preprocessing/heuristic_%A_%a.out
#SBATCH --error=logs/k_cut_preprocessing/heuristic_%A_%a.err

module load Gurobi

export OMP_NUM_THREADS=96

SCRIPT_DIR="slurm"
source "$SCRIPT_DIR/configs.sh"

i=${SLURM_ARRAY_TASK_ID}
seed=$((i-1))

for inst in "${instances_large[@]}"; do
  for kval in "${k[@]}"; do
    for presol in "${basic_presolve[@]}"; do
      if [ ! -e output/heuristic_"$inst"_"$kval"_"$presol"_"$seed".txt ]; then
        touch output/heuristic_"$inst"_"$kval"_"$presol"_"$seed".txt
        echo "Running ./build/heuristicBenchmark -i instances/instances_clean/$inst -o output/heuristic_"$inst"_"$kval"_"$presol"_"$seed".txt -k $kval -d $presol -s $seed -t 7200"
        ./build/heuristicBenchmark -i instances/instances_clean/$inst -o output/heuristic_"$inst"_"$kval"_"$presol"_"$seed".txt -k $kval -d $presol -s $seed -t 7200
      fi
    done
  done
done
